FROM fedora:latest

RUN dnf install -y 'dnf-command(copr)' && dnf copr enable -y vbatts/envoy && dnf install -y envoy curl
RUN dnf install -y python-pip python-requests
RUN pip install -q Flask==0.11.1
RUN mkdir /code
ADD ./service.py /code
ADD ./start_service.sh /usr/local/bin/start_service.sh
RUN chmod u+x /usr/local/bin/start_service.sh
ENTRYPOINT /usr/local/bin/start_service.sh
